version: '3.9'
services:
  trello_db:
    restart: always
    container_name: trello_db
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - next

networks:
  next:
    driver: bridge
